### ISSUE TITLE
Excalidraw SVG Light/Dark Mode support

### ISSUE THREAD

**Issue by cmorg789** [KosmosisDire/obsidian-webpage-export#103]
Currently, when exporting a document with embedded Excalidraw images, it will use the one matching the theme of obsidian by default. Excalidraw settings can be used to set it to dark or light mode, or add a background, which works as a workaround.

Excalidraw has an export setting to export both Light and Dark mode SVGs, this could be used to switch theme mode when exported.

**Comment by KosmosisDire** [comment]
Thanks for the suggestion. I'll look into making this work in the future

**Comment by dgudim** [comment]
Quick suggestion: replace svg hard-coded colors with ```var(--whatever)``` and use that for theme switching
(That's what I use for my svgs)

**Comment by KosmosisDire** [comment]
How are the dark and light Excalidraw SVGs handled in obsidian itself? Does the Excalidraw plugin programatically replace the SVGs instead of using styles? If it uses styles already you could just include those styles in the export. If it doesn't use styles, then I can look into auto replacing them, but you could also just writea snippet to style them differently in dark mode and light mode. But I will look into the problem and see if it is actually something that I should fix or leave it up to the user

**Comment by dgudim** [comment]
No idea, I use this method for svgs I download or make in inkscape

**Comment by KosmosisDire** [comment]
This should be implemented in v1.7.1! Let me know if you have any problems with it
