### ISSUE TITLE
jquery error when clicking on a link  in outline right sidebar

### ISSUE THREAD

**Issue by sergeBoisse** [KosmosisDire/obsidian-webpage-export#18]
Thank you for this amazing plugin ! I was able to run it,  and I am trying to use it to convert my entire vault into a website that would be an alternative to Obsidian publish. I was previouly trying to use Obsidian-share, but your plugin is better because it converts the output of mathjax, desmos, dataview, and even music-abc plugins seamlessly to html, and it handles callouts nicely !

I had an error in jquery (visible in chrome debugger) because I am trying to integrate the generated html code  into a more general website framework that also use the class "internal-link". The error comes when I click on a paragraph title in the outline right panel.

But I finally found a solution : 
in the file  "webpage.js" just replace the line

`$(".internal-link").on("click", function()`

with 

`$("outline-item-contents").on("click", function()`

Just because each element of your outline has both css classes "outline-item-content" and ".internal-link", but the latter is far more subject to be also used by divs that do not belonging to the outline column
Hope this helps and regards
Serge

**Comment by KosmosisDire** [comment]
That has to stay as .internal-link because it needs to run when **any** internal link directed to a header is clicked both inside and outside of the outline! That function actually unfolds the header if it has been collapsed when a link is clicked directed to that header. That needs to happen even if its just a link in the document itself that was clicked. I think there is something else going on here, but thank you for bringing it to my attention!

Out of curiosity what are the names of the headers that throw the error? I can only get it to throw the error on headers with non alphabetical characters in them like `Topics:` or `This / That` or `Here & There`.

This also means that this error doesn't break anything except that those headers won't fold out if they are collapsed when someone clicks a link that directs to that header.

I'll definitely fix this though, Thanks!

**Comment by sergeBoisse** [comment]
Thank you for your fast reply. Ah ! The header was in french, and reads "Y a quoi là dedans ?" which means "What's inside ?" Note the accent on the "à", and the question mark.

**Comment by KosmosisDire** [comment]
This should now be fixed. Thanks!
