### ISSUE TITLE
obsidian-excel Plugin Unable to display properly during export（obsidianV1.3.5 Plugin V1.6）

### ISSUE THREAD

**Issue by zhoulonghao520** [KosmosisDire/obsidian-webpage-export#249]
https://github.com/ljcoder2015/obsidian-excel

![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/f19278b3-1e6f-4b8b-904d-ad3e65df7c9e)

![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/f8c2c40e-72a3-4a9d-b7c0-b9b170bace09)

![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/10b58539-2c4e-47aa-8a4a-4db20d0d0218)

<img width="1623" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/ac5a8ee2-0e60-4c81-a81c-d5a60d765744">

Why cannot the content be displayed normally like other plugins after export.

obsidian：V1.3.5
Plugin: v1.6

**Comment by KosmosisDire** [comment]
Hi, thanks. Many plugins do things in their own way and so it is impossible for me to support every 3rd party plugin. It is possible that the plugin would work in the latest versions of the export plugin as I made some fixes to custom plugin views, however since you are using an old version of the plugin there isn't much I can do.

**Comment by KosmosisDire** [comment]
Hi I tested this and I am able to reproduce the problem. The reason it doesn't work is because this table is being rendered using an html canvas element. The table is not actually made out of html and so it is not possible to convert it to html. The best you can do is to include an image of the table.

**Comment by zhoulonghao520** [comment]
Thank you for your reply
