### ISSUE TITLE
Name decode error

### ISSUE THREAD

**Issue by I2rys** [KosmosisDire/obsidian-webpage-export#347]
**Describe the bug**
It seems like If you add a percentage sign or % in a file name It will error but it was able to export it successfully which is weird. Why error when It can export it successfully right?

**Operating System**
Windows 10

**To Reproduce**
Make any file with % in It's name.

### IMPORTANT: Error Log
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/87125939/2a1518d9-d674-4817-bc8a-6cf030c3419f)

**Comment by KosmosisDire** [comment]
Ah, this is because URLs are encoded using percent signs. The error is there because it fails to decode the percentage code (because there isn't one) but then the error is handled so that it works.

Really all this means is I should make it not display this error since it is being handled correctly. There is no actual problem and like you said the export is working as intended.

**Comment by I2rys** [comment]
> Ah, this is because URLs are encoded using percent signs. The error is there because it fails to decode the percentage code (because there isn't one) but then the error is handled so that it works.
> 
> Really all this means is I should make it not display this error since it is being handled correctly. There is no actual problem and like you said the export is working as intended.

I see and yup you should just make it ignore the errors when It decodes names that has percent signs.

**Comment by KosmosisDire** [comment]
Hey, can you verify this is vixed in the beta version 1.8.0-10b?

**Comment by I2rys** [comment]
I can confirm this bug has been fixed. Thank you!
