### ISSUE TITLE
[Bug]: Loss of function. Export File Name

### ISSUE THREAD

**Issue by ThomasLudwig** [KosmosisDire/obsidian-webpage-export#411]
### What happened?

With the previous version (1.7 i believe) I could choose between 2 file name formats 
- "_This%20is%20My%20title.html_"
- "_this-is-my-title.html_"

We the latest version I can only have the latter

This break the hard-links that I have set up

### Reproduction

Export the whole vault to a website

### Last Working Version

1.7

### Version

1.8.01

### Operating System

Win11

### Obsidian Version

1.4.5

### Relevant log output

```yaml
N/A
```

**Comment by KosmosisDire** [comment]
Hi, is this a matter of you wanting to use the first version, or is it a matter of you creating links using the first version already and not wanting the urls to change?

**Comment by ThomasLudwig** [comment]
Hi,
I used the first version for a long time. So not being able to keep using it breaks some of the links I put on other sites.

If it is too much work I'll update everything (I understand that with some locales/characters it can be a hassle), but as a user it felt more like a feature that was simply disabled.

**Comment by KosmosisDire** [comment]
I basically was a feature that was disabled, however you are right that I disabled it because I wanted to simplify the naming convention to reduce edge cases in the code and make exports more uniform. 

The setting still exists however, and you can change it by manually modifying the "makeNamesWebStyle" parameter in the data.json file contained in the plugin's directory. I don't beleive this should break anything if you disable it but I can't make any guarentees.

Thanks for the feedback :)

**Comment by ThomasLudwig** [comment]
Setting makeNamesWebStyle to "true" works ! Thanks
