### ISSUE TITLE
About a momentary black screen

### ISSUE THREAD

**Issue by youkoutaku** [KosmosisDire/obsidian-webpage-export#48]
**Describe the bug**
Using the light theme, there is a momentary black screen when viewing a new page via a hyperlink or refresh page on the exported html files. It looks like that the theme has changed.  If I use dark theme, it's no problem.

**Operating System**
I'm using the Microsoft Edge on Win11.

**To Reproduce**
1. Select an obsidian file that has some hyperlinks.
2. Export to HTML
3. Click on the HTML 
4. Use the light theme
5. Click a hyperlink or refresh page
6. See error

**Comment by youkoutaku** [comment]
Sorry, but I have discovered that the problem may be related to the obsidian theme at the time of export. 

If the obsidian is a dark theme at the time of export, and the exported file is viewed with light theme, when refreshing or going to a new page, it will return to the dark theme for a moment.

**Comment by KosmosisDire** [comment]
Yeah there is no way around this since there has to be some "default" theme and then the theme is changed via script. I have tried finding a way around this so that it is changed before it is even loaded but I haven't been able to find anything. I would love if this was able to be fixed though, so I'll leave this open for now. I would be happy to accept aPR that fixes this.

**Comment by youkoutaku** [comment]
Thank you for your reply. I am sorry that with my current knowledge, I am not able to solve this problem. I will continue to learn about it and hope to solve it in the future.

 Finally thank you very much for your work. I used it and posted the exported html in my blog.

**Comment by KosmosisDire** [comment]
Closing to be replaced by this more up to date issue #107
