### ISSUE TITLE
Export does not wait for dataview to render + URI malformed error

### ISSUE THREAD

**Issue by tyf2018** [KosmosisDire/obsidian-webpage-export#78]
Thank you for your prompt response and update. However, I am still encountering issues when exporting. I have two note libraries, and the issues vary depending on the number of notes.

Operating System
Win10.
Obsidian 1.2.6

1. Library with a small number of notes (approximately 500 notes): Generally, it can be exported normally, but when encountering complex dataview codes, the export will still result in a blank output without errors report. The compressed file below contains the dataview code, exported HTML file, and console log. 
[dataviewJS-test2023-05-02.zip](https://github.com/KosmosisDire/obsidian-webpage-export/files/11368800/dataviewJS-test2023-05-02.zip)

2. The other library is relatively larger, with over 11,000 notes. When exporting, an error message occurs immediately. 
![image](https://user-images.githubusercontent.com/56342788/235554657-92545b67-427d-4403-8479-ec597b6faddb.png)

Best regards.

_Originally posted by @tyf2018 in https://github.com/KosmosisDire/obsidian-webpage-export/issues/73#issuecomment-1530686380_

**Comment by KosmosisDire** [comment]
Thank you, it seems this is due to Chinese character as I can reproduce this when I name one of the exported files using Chinese characters. If you want you can revert to the version before 1.5.0 since it probably worked then. I rewrote the pathing system which probably intruduced a bug with non-latin characters. 

I am going to guess the dataview is causing errors when it loads a link to a file that uses Chinese characters?

**Comment by KosmosisDire** [comment]
Okay actually it looks like it isn't a problem in links, only in filenames. If you could verify that you can export just one file without Chinese characters, and that it breaks when it does have them that would be awesome. Thanks!

**Comment by KosmosisDire** [comment]
Okay it is actually because even once the file is rendered the dataview has not loaded yet, so I need to somehow wait until not only the page has rendered but also until the dataview has loaded to export. I am not sure what is casing the other error but I am pretty sure that it the first problem.

**Comment by tyf2018** [comment]
> If you want you can revert to the version before 1.5.0

Yes, in the past versions, even complex dataview code could be exported successfully in libraries with fewer notes. However, even with the old plugin, it couldn't handle complex dataview code in libraries with a large number of notes and only exported blank results. I think it might be a performance issue because dataview rendering itself takes 5-8 seconds in such cases.



> it seems to export them fine with Chinese characters

Yes, I don't think it's caused by Chinese characters because the same file (with file name and content containing a large number of Chinese characters) can be exported normally in my smaller library.

**Comment by KosmosisDire** [comment]
Yes, I am not really sure how to detect whether the dataview has been fully rendered, and I definetly cannot just add a flat wait time to the rendering as that would increase the time by a huge amount. I think part of the reason it worked before was because I was using a flat wait time that was too high, which likely left enough time for the dataview to render. As a temporary workaround I could try just detecting whether there is a dataview block in a file and add like 3 seconds per dataview block in the file. It would probably increase the time to export quite a lot if you have dataview blocks, but it would also make it so they would export correctly.

**Comment by KosmosisDire** [comment]
As far as the large export with the error, I think that is a different issue. I will make an update that will also display which file caused the error which will make it easier to track down what is causing that. Thanks for your patience with this 😊

**Comment by tyf2018** [comment]
Could you consider adding a setting option for users to choose the rendering waiting time?

**Comment by KosmosisDire** [comment]
I think since this is a problem that is proportional only to dataview blocks, I will add a waiting time per dataview block as that should keep the times low as possible. But I will make it so it can be set to any number of seconds per block. Or do you think a flat wait time across all files regardless of the number of dataview blocks would be better?

**Comment by tyf2018** [comment]
> I would add an option for the number of seconds to wait to render each dataview block

That would be great.

**Comment by KosmosisDire** [comment]
Hey, I added this in the latest release, let me know how it works. In my testing this was able to reliably fix the rendering issue with dataview queries. 

As far as your second issue where it thew an error I have added much better bedugging support to the export which shoud allow you to submit a better report if it is still a problem. It also should be less likely to halt the whole export process. If you do still encounter that error on your large vault, please copy the log from the new version and submit it in a new issue. Thanks!

**Comment by tyf2018** [comment]
It seems that there may still be mistakes.

```
URIError: URI malformed
    at decodeURI (<anonymous>)
    at _Path.parsePath (plugin:webpage-html-export:10237:12)
    at _Path.reparse (plugin:webpage-html-export:10216:24)
    at new _Path (plugin:webpage-html-export:10203:10)
    at eval (plugin:webpage-html-export:10589:14)
    at Array.map (<anonymous>)
    at GraphGenerator.getGlobalGraph (plugin:webpage-html-export:10588:19)
    at HTMLGenerator.fillInHead (plugin:webpage-html-export:11849:33)
    at HTMLGenerator.generateWebpage (plugin:webpage-html-export:11722:16)
    at async HTMLExportPlugin.exportFile (plugin:webpage-html-export:12306:7)
```

**Comment by KosmosisDire** [comment]
Hmm okay, at least I now know that that is triggered while generating the graph view. I think if you turn off the graph view this error should go away. Let me add a thing to print what path actually is causing the error and then we can continue to figure out what the problem is. But for now turn off the graph view to bypass it.

**Comment by tyf2018** [comment]
Thank you. After turning off the graph view, exporting normally should be possible in most cases. However, if encountering more complex dataview rendering results (the code consumes a lot of computer resources, and rendering the results itself takes about 5-10 seconds), although there are no error messages, the export result may still be blank.

**Comment by KosmosisDire** [comment]
Have you tried turning up the dataview render time? It is a value you can turn up higher to account for even more complex queries.

**Comment by tyf2018** [comment]
I set the waiting time to 20 seconds, but the export result is still blank. This is the console log.
![image](https://user-images.githubusercontent.com/56342788/236370288-a374ffc1-bdce-4424-98ce-a94ce3658c4b.png)

[obsidian.md-1683255934292.log](https://github.com/KosmosisDire/obsidian-webpage-export/files/11403000/obsidian.md-1683255934292.log)
